### ISSUE TITLE
ChatGPT now has a session history, and this extension adds a new session everytime i used it

### ISSUE THREAD

**Issue by etherealxx** [clmnin/summarize.site#11]
![image](https://user-images.githubusercontent.com/64251396/208964913-e0f4e678-f4c3-465c-953e-9ba4312c1562.png)

![image](https://user-images.githubusercontent.com/64251396/208964980-b65c08b3-6f11-4930-a4da-5a7d36f0fb21.png)

**Comment by clmnin** [comment]
Would you like the extension to keep using the same extension? 

I had an idea where the user can manage sessions from the extension. Here is an example usecase:
1. User is doing some research on a topic. They have to read multiple sources and so uses summarize.site to get a summary of the stuff they read.
2. Wouldn't it be better if it could have ChatGPT has it's partner? The user could pass the articles they read to the same chatGPT session so that they can have a conversation on the topic with ChatGPT.

So, we could use session to make sure ChatGPT has context on what we just read. And ask it questions.

**Comment by etherealxx** [comment]
Sorry i don't quite understand your answer. For the record, ChatGPT for Google extension can works without adding a new session on user's session list
<img src="https://user-images.githubusercontent.com/64251396/209161343-efce7452-1154-4812-a293-a84b53e854c0.png" alt="209161343-efce7452-1154-4812-a293-a84b53e854c0" width="700"/>

Maybe instead summarize.site can write the prompt used to a txt file instead, and the user have an option to use it.
<img src="https://user-images.githubusercontent.com/64251396/209162765-4715e480-2363-4078-88f8-e9d55d0fd2df.png" alt="209162765-4715e480-2363-4078-88f8-e9d55d0fd2df" width="400"/>
maybe a clickable there

**Comment by clmnin** [comment]
This was fixed in 969d3c78eee58ece0fcc4ac49db719194e86f688
