### ISSUE TITLE
Always ask me to login chat.openai.com

### ISSUE THREAD

**Issue by kulorro** [clmnin/summarize.site#21]
Ask me to login chat.openai.com in every three or four using.

**Comment by clmnin** [comment]
The reason is because OpenAI frequently expires its access token when you are using free tier. You can try visiting https://chat.openai.com/ to see that you have to login again.

I'm closing this as I think this is the issue. 

One solution is to always open the ChatGPT [website](https://chat.openai.com/) when you open your browser so that you get the latest access token. After that the extension just works. No hassle.

Please re-open this issue if the above solution does not fix your issue.
